Document: galacticempire
Title: Debian galacticempire Manual
Author: <insert document author here>
Abstract: This manual describes what galacticempire is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/galacticempire/galacticempire.sgml.gz

Format: postscript
Files: /usr/share/doc/galacticempire/galacticempire.ps.gz

Format: text
Files: /usr/share/doc/galacticempire/galacticempire.text.gz

Format: HTML
Index: /usr/share/doc/galacticempire/html/index.html
Files: /usr/share/doc/galacticempire/html/*.html

  
